[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = ""
authors = ["{{ cookiecutter.author }}"]
readme = "README.md"
packages = [{include = "config"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.2"
django-import-export = "^3.2.0"
whitenoise = "^6.5.0"
django-environ = "^0.10.0"
python-dotenv = "^1.0.0"
django-extensions = "^3.2.3"
werkzeug = "^2.3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
